#!/usr/bin/env python
#
# Simple script which allows grepping of a twitter user's tweets
# 
import sys
import re
import twitter

# Check we've got an argument
if len(sys.argv) < 3:
	print "usage: tweetgrep <search pattern> <twitter handle>"
	sys.exit(1)

# Takes two arguments, the search pattern and the twitter handle
pattern = sys.argv[1]
user = sys.argv[2]
api = twitter.Api()
r = re.compile(pattern)

# Loop through the tweets and print one on each line
try:
	statuses = api.GetUserTimeline(user)
except twitter.TwitterError, e:
	print "Error: %s" % e
	sys.exit(1)
else:
	for s in statuses:
		if r.search(s.text):
			print s.text
